/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareListIdRouteImport } from './routes/share.$listId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareListIdRoute = ShareListIdRouteImport.update({
  id: '/share/$listId',
  path: '/share/$listId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/share/$listId': typeof ShareListIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/share/$listId': typeof ShareListIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/share/$listId': typeof ShareListIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/favoritos' | '/login' | '/share/$listId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favoritos' | '/login' | '/share/$listId'
  id: '__root__' | '/' | '/favoritos' | '/login' | '/share/$listId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritosRoute: typeof FavoritosRoute
  LoginRoute: typeof LoginRoute
  ShareListIdRoute: typeof ShareListIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$listId': {
      id: '/share/$listId'
      path: '/share/$listId'
      fullPath: '/share/$listId'
      preLoaderRoute: typeof ShareListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritosRoute: FavoritosRoute,
  LoginRoute: LoginRoute,
  ShareListIdRoute: ShareListIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
